version: '3'

services:
  backend:
    build:
      context: ./uploader-backend
      dockerfile: ./Dockerfile
    image: 'back-dev-image-name'
    ports:
      - '3001:3001'
  frontend:
    build:
      context: ./uploader-frontend
      dockerfile: ./Dockerfile
    image: 'front-dev-image-name'
    depends_on:
      - backend
    ports:
      - '3000:3000'
    links:
      - 'backend'
