version: '3'
services:
  nodejs-server:
    build:
      context: ./uploader-backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    container_name: node-uploader-backend-dev
    volumes:
       - ./uploader-backend:/usr/src/app/uploader-backend
       - /usr/src/app/uploader-backend/node_modules
  react-ui:
    build:
      context: ./uploader-frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    container_name: react-ui-dev
    stdin_open: true
    volumes:
       - ./uploader-frontend:/usr/src/app/uploader-frontend
       - /usr/src/app/uploader-frontend/node_modules