# https://medium.com/bb-tutorials-and-thoughts/react-local-development-with-docker-compose-5a247710f997
version: '3'

services:
  backend:
    build:
      context: ./uploader-backend
      dockerfile: ./Dockerfile.prod
    container_name: node-uploader-backend-prod
    ports:
      - '3001:3001'
  frontend:
    build:
      context: ./uploader-frontend
      dockerfile: ./Dockerfile.prod
    container_name: react-ui-prod
    depends_on:
      - backend
    ports:
      - '3000:3000'
    links:
      - 'backend'
